#!/bin/bash
set -e

name="$1"; shift
fn="/etc/apt/sources.list.d/$name.list"
echo "- Adding APT repo(s): $name => $fn"

test -e "$fn" || touch "$fn"
cp -pv "$fn" "$fn.new"

for repo in "$@"; do
	case "$repo" in
		deb*)
			if egrep "^$repo\$" "$fn"; then
				echo "- Already exists: [$name] $repo" >&2
				continue
			fi
			echo "- Adding source: [$name] $repo" >&2
			echo "$repo" >> "$fn.new"
			;;
		*://*.list)
			# appears to be a url, treat it as a remote include
			echo "- Adding sources from URL: [$name] $repo"
			curl -sL "$repo" | tee -a "$fn.new"
			;;
	esac
done

if cmp "$fn.new" "$fn"; then
	rm -fv "$fn.new"
else
	mv -v "$fn.new" "$fn"

	# Force an apt update to occur next lazy-apt
	image-cleanup
fi
